new endpoints for custom registration
WardCunningham/wiki-plugin-register pull request #9
Opened 2023-09-06 14:43 UTC by WardCunningham

Here we propose a third style of Registration, "custom", to join the existing "owner" and "delegate" versions. This is in support of a proposal described in wiki:
http://ward.asia.wiki.org/custom-registration-workflow.html

The wiki documentation describes a collaboration between a community leader and the service operators. This pull request represents additional enabling work by the federated wiki developers required to enable the workflow to progress without further enhancement of core javascript or standard plugins on a case by case basis.

2023-09-06 16:11 UTC, paul90 requested changes
500 is the wrong error, it is either not yet implemented (501), or unavailable (503). Also no need to add different text to the response.

2023-09-06 16:11 UTC, paul90 commented on server/server.coffee
> +    e500 = (msg) -> res.status(500).send(msg)
would be better to use `501 Not Implemented` or `503 Service Unavailable` rather than `500 Internal Server Error`.

2023-09-06 16:11 UTC, paul90 commented on server/server.coffee
> +    e500 = (msg) -> res.status(500).send(msg)
See above.

2023-09-08 20:03 UTC, WardCunningham commented
Now with update [e12d34a](https://github.com/WardCunningham/wiki-plugin-register/pull/9/commits/e12d34ab3421e6441cc5d586f259a9af51165338) which loads the register.js but fails to run it successfully.

This is the test case implementation plan:
http://crazy.fed.wiki/view/ward-cunningham

I've installed register.js on localhost:

```
// sample register module for custom demo

export async function post(data) {
  return 'ok'
}
```

I invoked it with curl which stalls out without responding:

```
% curl -v -d '{"data":1,"context":2}' -H "Content-Type: application/json" http://localhost:3000/plugin/register/custom
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /plugin/register/custom HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.87.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 22
> 
^C
```

The server log shows that the test case module has loaded but the invocation never returns. Is this me confusing coffeescript and es6 javascript?

```
custom post {
  context: 2,
  data: 1,
  custom: [Module: null prototype] { post: [AsyncFunction: post] }
}
POST /plugin/register/custom - - - - ms
```

2025-12-07 10:17 UTC, merged